```{r}

library("nycflights13")
library("tidyverse")
View(planes)
```
1.) Inner-join
1.1) Conecte flights con planes
```{r}
inner_join(flights,planes,by=c("tailnum" = "tailnum"))
```
1.2) Conectar flights con airlines
```{r}
inner_join(flights,airlines,by=c("carrier" = "carrier"))
```
1.3) Conectar flights con airports
```{r}
inner_join(flights,airports,by=c("origin" = "faa"))
inner_join(flights,airports,by=c("dest" = "faa"))

```

1.4) Conectar flights con weather
```{r}
flights %>%
  inner_join(weather, flights, by=c("year", "month", "day", "hour", "origin"))
```

2.) Data manipulation
2.1) 
```{r}
count(flights, year, month, day) %>%
  filter(n > 1000) %>%
  arrange(n)
```
2.2) 
```{r}
flights_selected <- flights %>%
  select(year:day, hour,origin, dest, tailnum, carrier, arr_delay, dep_delay)
flights_selected
```

2.3) 
```{r}

left_join(airlines, flights_selected) %>%
  select(-origin,-dest) %>%
  mutate(tot_delay = arr_delay+dep_delay)


```
2.4
```{r}
precip_delay <- flights %>%
  inner_join(weather, by=c("year", "month", "day", "hour", "origin")) %>%
  group_by(precip) %>%
  summarise(delay=mean(dep_delay, na.rm=TRUE))


precip_delay

```

2.5
```{r}
library("ggplot2")
ggplot(precip_delay, aes(x=precip, y=delay)) + 
  geom_point()
```
2.6)
```{r}
flights_airports <- flights %>%
  filter(flights,year ==2013, ) %>%
  group_by(dest) %>%
  summarise(delay = mean(arr_delay, na.rm=TRUE))
```
2.7)

```{r}
ggplot(flights_airports, aes(x=lon, y=lat, color = delay)) + 
  geom_point()
```


2.8)
```{r}
flights %>%
  inner_join(planes, by="tailnum") %>%
  transmute(tailnum, manufacturer, pi=(dep_delay + arr_delay)/air_time)
```

