Arithmetic wth R

```{r}
5 + 5
10-2
3*5
(5+5)/2
28%%6
```

variable assignment
```{r}
x <- 10
x


y <- 9


```
Basics data type in R

```{r}
my_numeric <- 423.80

my_character <- "universe"

my_logical <- FALSE

class(my_numeric)
class(my_character)
class(my_logical)
```

Create a vector
```{r}
numeric_vector <- c(1,10,50)
numeric_vector

character_vector <- c("a","b","c")

boolean_vector <- c(TRUE,FALSE,TRUE)

character_vector
boolean_vector


poker_vector <- c(140, -9, 63,-45,26)
roulette_vector <- c(-58,36,74,36,96)

poker_vector
```

Naming a vector
```{r}
names(poker_vector) <- c("Monday","Tuesday","Wednsday", "Thursday", "Friday")
poker_vector

names(roulette_vector) <- c("Monday","Tuesday","Wednsday", "Thursday", "Friday")
roulette_vector
```

Selection by comparation
```{r}
age <- 21
age >= 18

selection_vector <- poker_vector > 0
selection_vector

poker_winning_days <- poker_vector[selection_vector]
poker_winning_days
```
Calculating
```{r}
x_vector <- c(4,7,9)
y_vector <- c(12,45,78)

result_vector <- y_vector + x_vector
result_vector 
```
vector selection
```{r}
poker_vector
poker_vector[3]
poker_vector[c(2,3,4)]
poker_vector[2:5]
```
Matrices

```{r}
matrix(1:8, byrow = TRUE, nrow=4)
```

analyze matrices
```{r}
new_hope <- c(48.123, 314.4)
empire_strikes <- c(270.45, 241.63)
return_jedi <- c(963.20, 1475.65)

box_office <- c(new_hope, empire_strikes, return_jedi)
box_office

stars_wars_matrix <- matrix(box_office, byrow = TRUE, nrow =3)
stars_wars_matrix
```

```{r}
region <- c("us","non-us")
titles <- c("a new hope", "the empire strikes back", "return of the jedi")

colnames(stars_wars_matrix) <- region
stars_wars_matrix
rownames(stars_wars_matrix) <- titles
```

rowSums
```{r}
rowSums(stars_wars_matrix)
colSums(stars_wars_matrix)
```

cbind and rbind

```{r}
total_revenue_by_title <- rowSums(stars_wars_matrix)
total_revenue_by_region <- colSums(stars_wars_matrix)

total <- cbind(stars_wars_matrix, total_revenue_by_title)
total <- rbind(tota, total_revenue_by_region)
total
```

selection of matrix elements
```{r}


stars_wars_matrix

stars_wars_matrix[1,1]
stars_wars_matrix[1:2, 2]

stars_wars_matrix[c(1,3),1]
stars_wars_matrix[c(1,3),]

```

Arithmetic with matrices

```{r}

mean <- stars_wars_matrix/5
mean *2
```
Factor
```{r}
sex_vector <- c("male", "female", "female","male", "male")
factor_sex_vector <- factor(sex_vector)
factor_sex_vector

```

```{r}
temperature_vector <- c("high", "low", "high", "low", "medium")
factor_temperature_vector <- factor(temperature_vector,order = TRUE, levels =c("low", "medium", "high"))
factor_temperature_vector
```
Factor levels

```{r}
survey_vector <- c("M", "F", "F", "M", "M")
factor_survey_vector <- factor(survey_vector)
factor_survey_vector
levels(factor_survey_vector) <- c("Female", "Male")
```

Summary
```{r}
summary(factor_survey_vector)
```

Ordered factors

```{r}
male <- factor_survey_vector[1]
female <- factor_survey_vector[2]

male
female

speed_vector <- c("medium", "slow", "high", "fast")
factor_speed_vector <- factor(speed_vector, order =TRUE, levels =c("slow", "medium","high", "fast"))
factor_speed_vector

speed_1 <- factor_speed_vector[2]
speed_5 <- factor_speed_vector[4]
speed_1
speed_5

speed_1 < speed_5
speed_5 < speed_1
```

