```{r}

View(mtcars)
str(mtcars)

```

CREAGIN A DATA FRAME

```{r}
name <- c("Mercury","Venus", "Earth", "Mars", "Jupiter", "Saturn", "Uranus", "Neptune")
type <- c("terrestrial planet", "terrestrial planet", "Terrestrial planet", "Terrestrial planet", "Gas giant", "Gas giant", "Gas giant", "Gas giant")
diameter <- c(0.91, 0.63, 2.29, 6.21, 5.23, 4.87, 7.36, 9.63)
rotation <- c(26.78, 256.9, 963.4, -875.4, 4.6, -74.2, 0.85, -52.1)
rings <- c(FALSE, FALSE, FALSE, FALSE, TRUE, TRUE, TRUE, FALSE)

planets_df = data.frame(name,type,diameter,rotation,rings)

View(planets_df)
planets_df
```
Selection of a data frame elements

```{r}
planets_df[1,3]
planets_df[4,]
planets_df[1:4, 3]
planets_df[1:5, "diameter"]

rings_vector <- planets_df$rings

planets_df[!rings_vector, ]

subset(planets_df, subset = rings ==TRUE)



```


Storing

```{r}
a <- c(100, 10, 1000)
order(a)

a[order(a)]

positions <- order(planets_df$diameter)
positions

planets_df[positions, ]
```
Lists

```{r}
my_vector <- 1:10
my_vector

my_matrix <- matrix(1:9, ncol=3)
my_df <- mtcars[1:10,]

my_list <- list(my_vector, my_matrix, my_df)
my_list

names(my_list) <- c("vec","mat", "df")
my_list
```

```{r}
mov <- c("The Shining")
act <- matrix(c("Jack Nicholson","Shelley Duvall","Danny Lloyd","Scatman Crothers","Barry Nelson"))

scores <- c(4.5, 5,4)
sources <- c("IMDb1", "IMDb2", "IMDb3")
comments <- c("Best Horros Film I have Ever Seen", "Atruly brilliant and scary film from stanley kubrick", "A masterpiece of psychological horror")

rev <- data.frame(scores, sources, comments)

shining_list <- list(moviename = mov, actors=act, reviews=rev)
shining_list
```

Selecting

```{r}
shining_list[[2]][1]
```

