EQUALITY
```{r}
"Rchietc" != "rchitect"

-6 * 14 !=17 -101
TRUE == 1

-6*5+2 >= -10+1
"raining" = "raining dogs"
TRUE < FALSE
```

COMPARE VECTORS
```{r}
linkedin = c(15,7,9,4,63,41,75)
facebook = c(85,96,74,12,45,79,5)

linkedin > 15
facebook <= 5
```

COMPARE MATRIZ
```{r}
views = matrix(c(linkedin, facebook), nrow=2,byrow=TRUE)
views

views == 13

views <= 14
```
& and |

```{r}
linkedin
last = tail(linkedin,3) #ultimos 3 valores almacenados
last

last = head(linkedin,3) #primeros 3 valores almacenados
last

last > 5 | last < 10
last > 15 & last <= 20

linkedin > 10 & facebook < 10
linkedin >= 12 | facebook >= 12
```
THE IF STATMENT

```{r}
medium = "linkedin"
num_views = 14

if(medium == "linkedin"){
  print("Showing linkedin information")
}else if(medium == "Facebook"){
  print("Showing Facebook information")
}else{
  print("Unknow medium")
}

if(num_views > 15){
  print("you are popular")
} else if(num_views <= 15 & num_views > 10){
  print("your number of views is average")
} else{
  print("try to ve more visible")
}
```
```{r}
result = ""
number = 6

if(number<10){
  if(number<5){
    result = "extra small"
  }
else{
  result = "small"
  }
} else if(number<100){
  result = "medium"
} else{
  result = "large"
}
print(result)
```

WRITE A WHILE A LOOP
```{r}
speed = 64

while (speed>30){
  print(paste("your speed is", speed))
  if(speed >= 48) {
    print("Slow down big time!")
    speed = speed-11
  } else{
    print("slow down!")
    speed = speed-6
  }
}
```

STOP THE WHILE LOOP: BREAK
```{r}
speed = 75

while (speed>30){
  print(paste("your speed is", speed))
  
  if(speed>80){
    break
  }
  if(speed>48){
    print("slow down big time!")
    speed = speed-11
  } else{
    print("slow down")
    speed=speed - 6
  }
}
```
BUILD A WHILE LOOP FROM SCRATCH
```{r}
i=1

while (i <= 10) {
  print(3*i)
  if((i*3)%% 8==0){
    break
  }
  i=i+1
}
```


LOOP OVER A VECTOR
```{r}
linkedin <- c(16,9,14,15,17,20,85)
for (l in linkedin){
  print(l)
}

for (i in 1:length(linkedin)){
  print(linkedin[i])
}
```

LOOP OVER A LIST
```{r}
nyc  <- list(pop = 788, boroughs = c("Manhathan", "Bronx", "Brooklyn","Queens","Staten Island"), capital =FALSE)
for(n in nyc){
  print(n)
}
for(i in 1:length(nyc)){
  print(nyc[i])
}

new_hope <- c(460.998,314.4)
empire_strikes <- c(290.475,247.900)
return_jedi <- c(309.306,165.8)

box_office  <- c(new_hope, empire_strikes, return_jedi)
box_office

stars_wars_matrix <- matrix(box_office, byrow = TRUE, nrow=3)
stars_wars_matrix


```
```{r}
region <- c("US", "non-US")
titles <- c("A new hope", "The empire strikes back", "Return of the Jedi")

colnames(stars_wars_matrix) <- region
rownames(stars_wars_matrix) <- titles
stars_wars_matrix
```
```{r}
for (i in 1:nrow(stars_wars_matrix)){
  for (j in 1:ncol(stars_wars_matrix)){
    print(paste("On Row", i, "and column", j, "the board contains", stars_wars_matrix[i,j]))
  }
}
```
```{r}
linkedin <- c(16,9,14,15,17,20,85)
for (li in linkedin){
  if(li > 10){
    print("you are popular")
  }
  else{
    print("be more visible")
  }
  if(li>16){
    print("this is ridiculous, im outta here")
    break
  }
  if(li>5){
    print("this is too emarrassing")
  }
  print(li)
}

```

